<?php
namespace KPG\RestAPI\Components\KPG\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Components(
    schemas: [
        new OA\Schema(ref: \KPG\RestAPI\Components\ILIAS\Category\OpenApi\Schema\GetCategoryResponseDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\Components\ILIAS\Category\OpenApi\Schema\GetCategorysResponseDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\Components\ILIAS\Group\OpenApi\Schema\GetGroupResponseDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\Components\ILIAS\Group\OpenApi\Schema\GetGroupsResponseDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\Components\ILIAS\Course\OpenApi\Schema\GetCourseResponseDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\Components\ILIAS\Course\OpenApi\Schema\GetCoursesResponseDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\OwnerNameSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\TitleSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\RefIdSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\RoleNameSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\PresentationTitleSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\OfflineStatusSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\ObjectTypeSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\LastUpdateDataSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\ParentIdSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\LongDescriptionSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\ImportIdSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\CreateDateSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\ResponseDefaultSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\ObjIdSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\OwnerSchema::class),
        new OA\Schema(ref: \KPG\RestAPI\API\OpenApi\Schema\DescriptionSchema::class),
    ],
    responses: [
        new OA\Response(ref: \KPG\RestAPI\Components\ILIAS\Category\OpenApi\Response\GetCategoryResponse::class),
        new OA\Response(ref: \KPG\RestAPI\Components\ILIAS\Category\OpenApi\Response\GetCategorysResponse::class),
        new OA\Response(ref: \KPG\RestAPI\Components\ILIAS\Group\OpenApi\Response\GetGroupResponse::class),
        new OA\Response(ref: \KPG\RestAPI\Components\ILIAS\Group\OpenApi\Response\GetGroupsResponse::class),
        new OA\Response(ref: \KPG\RestAPI\Components\ILIAS\Course\OpenApi\Response\GetCoursesResponse::class),
        new OA\Response(ref: \KPG\RestAPI\Components\ILIAS\Course\OpenApi\Response\GetCourseResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\TestNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\DefaultRoleNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\InternalServerErrorResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\UserLoginExistsResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\RoleNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\UserNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\ObjectNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\GroupNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\AuthFailedResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\RequierdFieldsNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\CreatedResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\AttributesNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\CategoryNotFoundResponse::class),
        new OA\Response(ref: \KPG\RestAPI\API\OpenApi\Response\CourseNotFoundResponse::class),
    ],
    parameters: [
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\FieldsParameter::class),
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\OrderParameter::class),
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\SearchParameter::class),
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\RefIDParamater::class),
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\LimitParameter::class),
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\OffsetParameter::class),
        new OA\Parameter(ref: \KPG\RestAPI\API\OpenApi\Parameter\FilterParameter::class),
    ],
    securitySchemes: [
        new OA\SecurityScheme(ref: \KPG\RestAPI\API\OpenApi\SecurityScheme\BasicSecurityScheme::class),
    ],
)]
final class Component {}
